### ISSUE TITLE
Revision use

### ISSUE THREAD

**Issue by fcastilloec** [electron-userland/electron-installer-common#19]
An issue reported on electron-installer-redhat made me realize that `options.revision` is not properly used.
It's mandatory for RPM but not for Debian, which means that we probably shouldn't load this option in the -common module.
Also, [defaults.js#L22](https://github.com/electron-userland/electron-installer-common/blob/master/src/defaults.js#L22) is loading the revision directly from the `package.json` but from what I've looked, this is not a field used there. It seems that `pkg.revision` was never part of `package.json`

So, I think we should remove `revision` from this module and move it to `-debian` and `-redhat`. It won't be read from `package.json` anymore, only from user's options. It will default to `1` for RPM and `undefined` for Debian.

@malept Thoughts?

**Comment by malept** [comment]
> It seems that `pkg.revision` was never part of `package.json`

`pkg.productName` was never part of `package.json` and yet it's used everywhere in the Electron ecosystem. `pkg.revision` has always been a part of most of the `electron-installer-*` modules since the beginning, and I don't really mind that it's there.

I've made a PR in #29 to fix the bug a different way.
